version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  db:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
