# Generated by Django 4.0 on 2022-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_cliente_sucursal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa_activa',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
