# Generated by Django 4.0 on 2022-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_empresa_empresa_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa_activa',
            field=models.BooleanField(verbose_name='activa'),
        ),
    ]
